"""Reusable analysis APIs and typed result objects."""

from dfr.analysis.dra import (
    DRAFrameSamples,
    FIT_MODELS,
    concatenate_frames,
    compute_dra_sweep,
    compute_scale_model_order_surface,
    create_scale_analysis,
    fit_design_matrix,
    fit_dra_surface,
    fit_frames,
    fit_one_surface_model,
    mean_nearest_neighbour_distance,
    model_orders,
    grouped_cv_rmse,
    leave_one_dataset_out_rmse,
    select_frames,
)
from dfr.analysis.results import (
    ManifoldAnalysisResult,
    ModeCurveResult,
    ScaleAnalysisResult,
)
from dfr.analysis.modes import analyze_dataset_modes, compute_mode_curve, count_modes
from dfr.analysis.manifold import (
    Centered3PLFitBatch,
    LegacyManifoldCache,
    PARAMETER_NAMES,
    centered_3pl_excess,
    fit_centered_3pl_curves,
    fit_shape_curve,
    load_legacy_manifold_cache,
    median_nearest_neighbour_distance,
    project_to_shape_curve,
    scale_for_mode_count,
)

__all__ = [
    "DRAFrameSamples",
    "Centered3PLFitBatch",
    "FIT_MODELS",
    "LegacyManifoldCache",
    "ManifoldAnalysisResult",
    "ModeCurveResult",
    "PARAMETER_NAMES",
    "ScaleAnalysisResult",
    "analyze_dataset_modes",
    "centered_3pl_excess",
    "concatenate_frames",
    "compute_scale_model_order_surface",
    "compute_mode_curve",
    "compute_dra_sweep",
    "count_modes",
    "create_scale_analysis",
    "fit_design_matrix",
    "fit_centered_3pl_curves",
    "fit_dra_surface",
    "fit_frames",
    "fit_one_surface_model",
    "fit_shape_curve",
    "grouped_cv_rmse",
    "leave_one_dataset_out_rmse",
    "load_legacy_manifold_cache",
    "mean_nearest_neighbour_distance",
    "median_nearest_neighbour_distance",
    "model_orders",
    "project_to_shape_curve",
    "scale_for_mode_count",
    "select_frames",
]
